apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # Wait for MySQL before starting backend (uses mysql client image)
      initContainers:
        - name: wait-for-mysql
          image: mariem360/portfolio-app-cicd-pipeline-backend:1.0.0-49
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."
              until mysqladmin ping -h mysql -uroot -p"$MYSQL_ROOT_PASSWORD" --silent; do
                sleep 3
              done
              echo "MySQL is up."
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

      containers:
        - name: backend
          image: mariem360/portfolio-app-cicd-pipeline-backend:1.0.0-49
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"

            # REQUIRED: point Spring to the mysql service (NOT localhost)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/Portfolio?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: portfolio
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
