apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mariem360/portfolio-app-cicd-pipeline-backend:1.0.0-42
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATASOURCE_USERNAME
              value: "test"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "pass"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: portfolio
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
