apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: portfolio
type: Opaque
stringData:
  MYSQL_DATABASE: "Portfolio"
  MYSQL_ROOT_PASSWORD: "test_pass"   
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "pass"
